version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  web:
    build: .
    depends_on:
      - db
    ports:
      - 50051:50051